name: Unit Tests (Fedora)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install System Packages
        run: |
          sudo dnf install -y util-linux-user
          sudo dnf install -y gfortran
          sudo dnf install -y clang
          sudo dnf install -y g++
          sudo dnf install -y wget
          sudo dnf install -y git
          sudo dnf install -y cmake
          sudo dnf install -y python3.10
          sudo dnf install -y scons

      - name: Change Shell
        run: |
          sudo chsh -s /bin/bash
          echo $SHELL

      - name: Install PyTorch
        run: |
          python3.10 -m venv venv_pytorch
          source venv_pytorch/bin/activate
          pip3 install torch==2.5.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          python -c "import torch; print(torch.__config__.show()); print(torch.__config__.parallel_info());"

      - name: Install LIBXSMM
        run: |
          git clone https://github.com/libxsmm/libxsmm.git
          cd libxsmm
          git log | head -n 25
          make BLAS=0 -j
          cd ..