name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  UT:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: PyTorch
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu